### ISSUE TITLE
NPM Install Fails with Error `[ERR_REQUIRE_ESM]: Must use import to load ES Module`

### ISSUE THREAD

**Issue by tcbutler320** [h-enk/doks#386]
## Description

When following the installation instructions on the readme, the NPM insall fails with an error "Must use import to load ES Module"

### Steps to reproduce

1) Clone the template 

```bash
git clone https://github.com/h-enk/doks.git my-doks-site && cd my-doks-site
```

2) Run npm install

```bash
npm install
```

### Expected result

What should happen?

### Actual result
```text
└─(20:21:46 on master ✹)──> git clone https://github.com/h-enk/doks.git my-doks-site && cd my-doks-site
```. 


```text
┌─(/tmp/my-doks-site)───────────────────────────────────────────────────────────────────────────────────────────────(tylerbutler@me:s000)─┐
└─(20:20:33 on master)──> npm install                                                                                       ──(Tue,Jul13)─┘
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> @hyas/doks@0.3.3 postinstall
> hugo-installer --version otherDependencies.hugo --extended

internal/modules/cjs/loader.js:1173
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/tmp/my-doks-site/node_modules/hugo-installer/bin/hugo-installer.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:13)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code 1
npm ERR! path /private/tmp/my-doks-site
npm ERR! command failed
npm ERR! command sh -c hugo-installer --version otherDependencies.hugo --extended

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tylerbutler/.npm/_logs/2021-07-14T00_20_47_995Z-debug.log
```

### Environment

```text
┌─(/tmp/my-doks-site)───────────────────────────────────────────────────────────────────────────────────────────────(tylerbutler@me:s000)─┐
└─(20:20:48 on master ✹)──> neofetch                                                                                    1 ↵ ──(Tue,Jul13)─┘
                    'c.          tylerbutler@me
                 ,xNMM.          --------------
               .OMMMMo           OS: macOS 11.4 20F71 x86_64
               OMMM0,            Host: MacBookPro15,2
     .;loddo:' loolloddol;.      Kernel: 20.5.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 3 days, 3 hours
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 137 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Purple (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: MesloLGMForPowerline-Regular 14
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i7-8569U (8) @ 2.80GHz
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel Iris Plus Graphics 655
       .cooc,.    .,coo:.        Memory: 9527MiB / 16384MiB
```

Paste the information here as shown by `npm run check`

```text
┌─(/tmp/my-doks-site)───────────────────────────────────────────────────────────────────────────────────────────────(tylerbutler@me:s000)─┐
└─(20:21:25 on master ✹)──> npm run check                                                                                   ──(Tue,Jul13)─┘

> @hyas/doks@0.3.3 precheck
> npm version

{
  '@hyas/doks': '0.3.3',
  npm: '7.12.1',
  node: '12.16.0',
  v8: '7.8.279.23-node.31',
  uv: '1.34.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.40.0',
  napi: '5',
  llhttp: '2.0.4',
  http_parser: '2.9.3',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}

> @hyas/doks@0.3.3 check
> exec-bin bin/hugo/hugo version

internal/modules/cjs/loader.js:1173
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/tmp/my-doks-site/node_modules/exec-bin/bin/exec-bin.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:13)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
┌─(/tmp/my-doks-site)───────────────────────────────────────────────────────────────────────────────────────────────(tylerbutler@me:s000)─┐
└─(20:21:46 on master ✹)──>
```

**Comment by h-enk** [comment]
Hi @tcbutler320, I can't reproduce the error you're facing. Would you mind trying w/ the LTS or current version of Node.js?

**Comment by tcbutler320** [comment]
No problem I'll try soon and report back, i think this is probably related to outdated node

**Comment by tcbutler320** [comment]
I upgraded to node v16.5.0 and that resolved the issue, thanks!

```text
└─(05:41:22)──> node --version                                                                                              ──(Fri,Jul16)─┘
v16.5.0
```
